import React, { useEffect } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { Report } from '../../types/report.types';
import ReportPrintView from './ReportPrintView';
import { reportToPrintInput, openReportPrintWindow } from '../../services/report-print';
import PageTransition from './PageTransition';

interface ReportPreviewProps {
  report: Report;
}

const ReportPreview: React.FC<ReportPreviewProps> = ({ report }) => {
  const navigate = useNavigate();
  const printInput = reportToPrintInput(report);

  // EXHIBIT: DM Sans is self-hosted and already loaded by index.html, so the
  // runtime Google Fonts <link> injection that used to live here is removed.

  const handleDownload = () => {
    openReportPrintWindow(printInput, report.title);
  };

  return (
    <PageTransition>
      <div className="min-h-screen bg-[#0F0F11]">
        {/* Top bar */}
        <div className="sticky top-0 z-10 bg-[#0F0F11]/80 backdrop-blur-md border-b border-white/[0.06] px-6 py-3 flex items-center gap-4">
          <button
            onClick={() => navigate({ to: '/' })}
            className="text-[13px] text-white/[0.50] hover:text-white/[0.80] transition-colors duration-150 flex items-center gap-1.5 focus:outline-none focus-visible:ring-1 focus-visible:ring-primary-200/50 rounded px-1"
            aria-label="Back to reports"
          >
            <i className="fa-solid fa-arrow-left text-xs" />
            Reports
          </button>

          <div className="flex-1 text-center">
            <h1 className="fb-h4 text-white/[0.92]">{report.title}</h1>
            {report.agentName && (
              <div className="flex items-center justify-center gap-1.5 mt-0.5">
                <i className="fa-solid fa-robot text-white/[0.30] text-xs" />
                <span className="text-[12px] text-white/[0.45]">Generated by {report.agentName}</span>
              </div>
            )}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() =>
                navigate({
                  to: '/report/$reportId',
                  params: { reportId: report.id } as never,
                })
              }
              className="text-[13px] text-white/[0.50] hover:text-white/[0.80] transition-colors duration-150 flex items-center gap-1.5 px-3 py-1.5 rounded-lg hover:bg-white/[0.04] focus:outline-none focus-visible:ring-1 focus-visible:ring-primary-200/50"
            >
              <i className="fa-solid fa-pen text-xs" />
              Edit
            </button>
            <button
              onClick={handleDownload}
              className="bg-primary-200 text-white text-[13px] font-medium px-4 py-2 rounded-lg flex items-center gap-1.5 hover:bg-primary-100 transition-colors duration-150 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-200 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0F0F11]"
              aria-label="Download PDF"
            >
              <i className="fa-solid fa-download text-xs" />
              Download PDF
            </button>
          </div>
        </div>

        {/* Report pages */}
        <div className="py-8 px-6">
          <div
            className="mx-auto"
            style={{ fontFamily: "'DM Sans', sans-serif" }}
          >
            <ReportPrintView data={printInput} previewMode />
          </div>
        </div>
      </div>
    </PageTransition>
  );
};

export default ReportPreview;
