/**
 * ORO Connect — the third case study.
 *
 * Same dark case-study shell as LIR and Verkos (it reuses <LirCaseStudy>), with
 * its own signal accent: gold #d9a441 (`accent: "gold"` → data-accent on the
 * .lir root). See the accent note in lirDesign.ts.
 *
 * ⚠️ THIS IS A REFRAME OF AN OLDER CASE STUDY, NOT A TRANSCRIPTION.
 * The original lives at rudyman.framer.website/oro and was written during the
 * internship itself. It runs audit → personas → IA → screens and closes on
 * three introspective learnings, with NO metrics anywhere — the work reads as a
 * sequence of tasks performed rather than a problem solved. The substance was
 * always there; the framing buried it.
 *
 * What changed here, deliberately:
 *   - A REFRAME chapter (03) now carries the thesis the original never stated:
 *     the product was built as an order form when the job was a catalogue.
 *     Everything downstream follows from that one line.
 *   - The four personas move from being the spine of the story to EVIDENCE
 *     inside Process — each is kept only for the decision it forced.
 *   - Impact leads with outcome instead of "this was the first time I had made
 *     something of this scale", which undercut the work before the reader had
 *     any result to weigh it against.
 *
 * ⚠️ NO OUTCOME METRICS, ON PURPOSE.
 * This shipped before any instrumentation existed, so there is no analytics to
 * quote and none is invented. The `stats` block carries SCOPE figures (70K+
 * designs, 4 segmented buyer types) rather than fake conversion numbers, and
 * Impact says plainly that the improvement is reasoned from the interaction
 * design rather than measured. Do NOT "upgrade" these to hard claims later
 * without real data — an invented number is the one change that would make this
 * study worse than the version it replaces.
 *
 * SOURCES (all first-party, from the internship deck + Figma):
 *   - the "Why?" problem framing, verbatim, including the business consequence
 *     line "ORO loses sales, incurs order errors, and wastes time on manual
 *     back-and-forth" — the impact statement the Framer write-up buried
 *   - four persona slides (R1 distributor · R2 boutique retailer · R3 corporate
 *     purchase head · R4 new-gen prospect) + the power-interest matrix that
 *     prioritised them
 *   - the solutions summary mapping each persona to the screens that serve it
 *   - the FigJam IA board and the shipped UI (landing, products, search, cart,
 *     reference numbers, design request)
 *
 * Assets are generated by `scripts/oro-assets.mjs`, which dark-corrects the
 * light-mode slide exports for this study's near-black canvas — see that file
 * for why a blanket invert is wrong and which images are protected.
 *
 * LirDesign-shaped so it drops straight into the STUDIES registry.
 */

import type { LirDesign } from "@/lib/caseStudies/lirDesign";

const A = "/case-study/oro"; // asset base — namespaced like Verkos, not flat like LIR

export const ORO_DESIGN: LirDesign = {
  slug: "oro-connect",
  backLabel: "Back to work",
  accent: "gold",

  // Opening cover plate. No `title`/`role` SVGs for this study — the cover
  // renders the title in the display face and the company/role as text from
  // `meta` instead. (The FlytBase studies have bespoke lockups; ORO does not,
  // and inventing one would mean drawing a brand mark that isn't theirs.)
  intro: {
    bg: `/case-study/cover/oro-cover-bg.webp`,
  },

  eyebrow:
    "B2B jewellery · bulk ordering · catalogue at scale · ORO Precious Metals",
  title: "ORO Connect",
  headline: "A 70,000-piece catalogue a buyer can actually shop",
  lede:
    "ORO manufactures its own line of gold and platinum jewellery and supplies retailers and distributors at scale. Their buyers were placing bulk orders through a system that made them recall exact SKUs from memory — and phone someone whenever it went wrong. Every one of those calls was a sale slowed down. I rebuilt ordering around discovery instead of data entry, across desktop and mobile, so the catalogue does the remembering.",

  // ⚠️ ESTIMATES / SCOPE FIGURES. See the file header — no instrumentation
  // existed, so nothing here claims a measured outcome.
  stats: [
    {
      value: "70K+",
      label: "Designs the catalogue had to stay shoppable at",
      sub: "Actual inventory scale — the constraint every screen was designed against",
    },
    {
      value: "4 buyer types",
      label: "Segmented, prioritised, and traced to shipped screens",
      sub: "Distributor · boutique retailer · corporate purchase head · new prospect",
    },
  ],

  // Overview cover — the real landing screen, bare (house rule: UI, no frame)
  cover: {
    id: "00-cover",
    src: `${A}/landing.webp`,
    label:
      "ORO Connect — the retailer landing page, opening on the brand and the catalogue rather than a bare search field.",
  },

  meta: [
    { label: "Company", value: "ORO Precious Metals" },
    { label: "Role", value: "UI/UX Designer" },
    { label: "Duration", value: "May–July 2025" },
    { label: "Status", value: "Live in production" },
    { label: "Team", value: "Solo, mentored" },
  ],

  // vestigial at render time (the rail derives itself) but kept for parity
  contents: [
    { n: "", label: "Overview", id: "overview" },
    { n: "01", label: "context", id: "context" },
    { n: "02", label: "problem", id: "problem" },
    { n: "03", label: "reframe", id: "reframe" },
    { n: "04", label: "process", id: "process" },
    { n: "05", label: "solution", id: "features" },
    { n: "06", label: "trade-offs", id: "decisions" },
    { n: "07", label: "impact", id: "impact" },
  ],

  buildStatement:
    "They were treating it as an order form. The job was a catalogue.",

  sections: [
    /* ── 01 CONTEXT ──────────────────────────────────────────────────────── */
    {
      kind: "prose",
      id: "context",
      n: "01",
      heading: "Context",
      blocks: [
        {
          t: "statement",
          text: "ORO's buyers were not shopping. They were filing paperwork.",
          full: true,
        },
        {
          t: "richP",
          spans: [
            { text: "ORO Precious Metals is a " },
            { text: "B2B jewellery manufacturer", bold: true },
            {
              text:
                " that designs and produces its own line of bangles and fine jewellery, supplying large-scale retailers and distributors across several markets. Traditional craftsmanship, modern design sensibilities, and an inventory big enough that no one person can hold it in their head.",
            },
          ],
        },
        {
          t: "p",
          text:
            "An ERP system and a companion mobile app already existed for bulk orders. Both worked, in the narrow sense that orders did eventually get placed. But the flow assumed the buyer already knew exactly what they wanted, down to the internal design number — and when that assumption broke, which was often, the fix was to call someone at ORO.",
        },
        { t: "sceneBreak" },
        {
          t: "statement",
          text:
            "Every order that needed a phone call was a design failure wearing a customer-service costume.",
        },
      ],
    },

    /* ── 02 PROBLEM ──────────────────────────────────────────────────────── */
    {
      kind: "prose",
      id: "problem",
      n: "02",
      heading: "Problem",
      blocks: [
        {
          t: "lede",
          text:
            "I audited the existing platform before proposing anything. The issues were not cosmetic — the structure itself was working against every kind of buyer, and each one failed differently.",
        },
        {
          t: "animatedDiagram",
          which: "oroFrictionMap",
          caption:
            "The problem framing I presented to stakeholders — how the fragmented ordering process fails each buyer segment, and what it costs ORO.",
        },
        {
          t: "p",
          text:
            "Small traditional shops struggled with complex online forms and feared typos when reordering exact SKUs. Mid-sized chains wanted light tweaks to curated designs but had no real-time pricing or clear mockups to work from. Large multi-store buyers needed a single source of truth — filterable specs, bulk RFQ uploads, transparent lead times — and instead clicked through dozens of pages. New prospects saw no concrete ROI, could not easily request samples, and endured slow partner-approval cycles.",
        },
        { t: "sceneBreak" },
        {
          t: "statement",
          text:
            "As a result, ORO loses sales, incurs order errors, and wastes time on manual back-and-forth.",
          full: true,
        },
        {
          t: "heading",
          text: "The system asked buyers to recall, not recognise",
        },
        {
          t: "p",
          text:
            "Ordering meant entering ORO's internal design numbers. A buyer placing a repeat order for a bangle they had sold for years still had to produce a code from memory or dig through a spreadsheet. Mistyped numbers meant wrong stock, and wrong stock on a bulk gold order is expensive in both money and trust.",
        },
        {
          t: "heading",
          text: "No design system, and the interface showed it",
        },
        {
          t: "p",
          text:
            "There was no shared component language in the previous app. Beyond the visual inconsistency, there were clear violations of Hick's and Fitt's laws throughout — choices multiplied where they should have been narrowed, and the controls people used constantly were no easier to hit than the ones they never touched. This had to be a design-first overhaul, not a reskin.",
        },
      ],
    },

    /* ── 03 REFRAME ──────────────────────────────────────────────────────── */
    {
      kind: "prose",
      id: "reframe",
      n: "03",
      heading: "Reframe",
      blocks: [
        {
          t: "quoteFlash",
          tone: "bright",
          wide: true,
          text:
            "It was built as an order form. The job was a catalogue.",
        },
        { t: "sceneBreak" },
        {
          t: "quote",
          text: "People don't see a website, they browse.",
          cite: "My manager, on why the landing page mattered",
        },
        { t: "sceneBreak" },
        {
          t: "microInteraction",
          which: "oroProductCard",
          caption:
            "On hover the specification panel gives way to a macro crop of the piece. On a wall of 70,000 near-identical bangles, you identify a design by its surface — not by memorising its number.",
        },
      ],
    },

    /* ── 04 PROCESS ──────────────────────────────────────────────────────── */
    {
      kind: "prose",
      id: "process",
      n: "04",
      heading: "Process",
      blocks: [
        {
          t: "lede",
          text:
            "I built four buyer profiles from stakeholder conversations. They are in this case study only because each one forced a specific decision — a persona that changes nothing is a slide, not research.",
        },
        {
          t: "matters",
          items: [
            {
              icon: "roles",
              title: "The traditional bulk buyer forced the reorder path",
              body:
                "Mohan, 52, not tech-savvy, reorders known lines and fears overstock. He is why reordering never requires typing a design number, and why past orders are a first-class surface rather than buried history.",
            },
            {
              icon: "context",
              title: "The brand-aware customiser forced visual reference",
              body:
                "Seema tweaks existing lines to protect brand equity and needs to see what she is changing. She is why customisation happens against an image with live pricing, not on a blank request form.",
            },
            {
              icon: "time",
              title: "The industry-pro buyer forced search at scale",
              body:
                "Rajiv compares suppliers, wants curated lines and bulk RFQs, and works from data. He is why search had to survive 70,000 entries and why minimum order quantities are stated up front rather than discovered in negotiation.",
            },
            {
              icon: "language",
              title: "The prospective retailer forced the case for ORO",
              body:
                "Khaled has never bought from ORO and is assessing whether it is worth starting. He is why the landing page leads with what ORO makes and why sampling has a route that does not begin with a sales call.",
            },
          ],
        },
        { t: "sceneBreak" },
        {
          t: "personaCarousel",
          personas: [
            {
              src: `${A}/persona-r1.webp`,
              name: "Mohan Patel",
              role: "R1 · The Traditional Bulk Buyer",
              alt:
                "R1 — the Traditional Bulk Buyer. Goals, behaviours, feelings and pain points for the not-tech-savvy shop owner who reorders known lines.",
            },
            {
              src: `${A}/persona-r2.webp`,
              name: "Seema Khurana",
              role: "R2 · The Brand-Aware Customiser",
              alt:
                "R2 — the Brand-Aware Customizer. Goals, behaviours, feelings and pain points for the boutique retailer who tweaks existing ORO lines.",
            },
            {
              src: `${A}/persona-r3.webp`,
              name: "Rajiv Menon",
              role: "R3 · The Industry-Pro Buyer",
              alt:
                "R3 — the Industry-Pro Buyer. Goals, behaviours, feelings and pain points for the data-driven buyer comparing suppliers at scale.",
            },
            {
              src: `${A}/persona-r4.webp`,
              name: "Khaled Rahman",
              role: "R4 · The Prospective Retailer",
              alt:
                "R4 — the Prospective Retailer. Goals, behaviours, feelings and pain points for the new prospect assessing whether to start with ORO.",
            },
          ],
        },
        {
          t: "p",
          text:
            "Segmenting mattered more than covering everyone. The system could not serve every buyer equally well, so I plotted them on a power-interest matrix with stakeholders and let that decide who wins when two needs conflict.",
        },
        {
          t: "media",
          slot: {
            id: "power-interest",
            src: `${A}/power-interest.webp`,
            label:
              "The power-interest matrix — R2 and R3 as key players, R1 needing to be met, R4 kept informed. This is what made the prioritisation a decision rather than a preference.",
          },
          wide: true,
        },
        { t: "sceneBreak" },
        {
          t: "heading",
          text: "Every persona traced to something that shipped",
        },
        {
          t: "p",
          text:
            "Research earns its place only if you can point at the interface and say which finding put it there. I kept an explicit map from each buyer's blocking problem to the screens that answer it — and a set of common solutions that serve all four at once.",
        },
        {
          t: "media",
          slot: {
            id: "solutions-summary",
            src: `${A}/solutions-summary.webp`,
            label:
              "Solutions summary — each persona's core problem mapped to the specific screens that resolve it, plus the common solutions shared across all four.",
          },
          wide: true,
        },
        { t: "sceneBreak" },
        {
          t: "heading",
          text: "Information architecture",
        },
        {
          t: "p",
          text:
            "Mapping the full flow was what made the scale of the problem legible. Once every moving piece was on one surface — catalogue, product collections, the configurator, retailer onboarding, cart, order history, and the two ID systems running underneath — it was obvious which screens were carrying more than they should.",
        },
        {
          t: "media",
          slot: {
            id: "ia-map",
            src: `${A}/ia-map.webp`,
            label:
              "The information architecture — the full service mapped end to end, prioritising user needs against business decisions to decide the flow and hierarchy.",
            caption:
              "Click to open full size — the tree covers the catalogue, configurator, retailer onboarding and account flows.",
          },
          wide: true,
        },
        {
          t: "p",
          text:
            "I used the Moon design system as the foundation rather than building components from scratch. With one designer and three months, inventing a component library would have consumed the time the actual problem needed — and the aesthetic already matched the direction I wanted.",
        },
        {
          t: "media",
          slot: {
            id: "process-whiteboard",
            src: `${A}/process-whiteboard.webp`,
            label:
              "Wireframing the reorder flow before committing anything to high fidelity.",
          },
        },
      ],
    },

    /* ── 05 SOLUTION / FEATURES ──────────────────────────────────────────── */
    {
      kind: "features",
      id: "features",
      n: "05",
      heading: "Solution",
      features: [
        {
          tagline: "People don't see a website, they browse.",
          title: "A landing page that opens on the brand",
          constraintLabel: "The constraint",
          constraint:
            "Stakeholders knew ORO's staples. Buyers did not know the rest of the catalogue existed.",
          body:
            "The landing page leads with ORO's world — the retail family, the craft, the collections — rather than a bare search field. A search field only helps someone who already knows what to type, and three of the four buyer profiles did not.",
          body2:
            "This is the screen that turns the product from a form into a catalogue. Everything downstream depends on the reader having somewhere to start.",
          textSide: "left",
          media: [
            {
              id: "feature-landing",
              src: `${A}/landing.webp`,
              label:
                "The retailer landing page — the brand and the invitation to join, before any transactional UI.",
            },
          ],
        },
        {
          tagline: "More than 70,000 designs, two tiers of filters.",
          title: "A products page built to survive the inventory",
          constraintLabel: "The constraint",
          constraint:
            "The site had to host more than 70,000 designs and still get a buyer to the right one.",
          body:
            "Hosting the full catalogue meant two separate tiers of filters — broad category narrowing first, then specific search parameters — so the page could load and stay usable at that scale rather than collapsing into an endless grid.",
          textSide: "right",
          media: [
            {
              id: "feature-products",
              src: `${A}/products.webp`,
              label:
                "The products page — filtered browsing across the full catalogue, with product cards showing the piece rather than a code.",
            },
          ],
        },
        {
          tagline: "Search by intent, because a static bar was useless here.",
          title: "Search that scopes itself, and cards that animate",
          constraintLabel: "The constraint",
          constraint:
            "A plain text search over 70,000 designs with matching initials would crash the backend — and a static search bar was unintuitive at that volume.",
          body:
            "The fix was filtering search results by intent: the buyer says whether they want this thing in products, orders, or cart, and the query is scoped before it is sent. The technical ceiling produced a better interaction than an unconstrained search would have.",
          body2:
            "The product cards carry ORO's own animation language — micro-interactions on hover that break information fatigue as the card goes from text to a smooth zoomed-in shot of the piece.",
          textSide: "left",
          media: [
            {
              id: "feature-search",
              src: `${A}/search-scoped.webp`,
              label:
                "Intent-scoped search over the catalogue — the query is narrowed to products, orders or cart before it is sent, and the cards below it carry the hover micro-interaction shown earlier.",
            },
          ],
        },
        {
          tagline: "The biggest challenge in the product.",
          title: "A cart that stays legible under load",
          constraintLabel: "The constraint",
          constraint:
            "Show a bulk order of unique tokens and IDs, each needing its own customer reference, without overwhelming the person approving it.",
          body:
            "The cart had to showcase a bulk order made of many unique items, each carrying its own custom reference number, against designs that already have a unique ID generated by the factory. Navigating existing flows and creating a seamless experience for this was the hardest and most enjoyable problem in the project.",
          textSide: "right",
          media: [
            {
              id: "feature-cart",
              src: `${A}/cart.webp`,
              label:
                "The cart — every line item with weight, price code and reference number, editable up to checkout, structured so a large order stays scannable.",
            },
          ],
        },
        {
          tagline: "Requesting something that does not exist yet.",
          title: "A design request flow that stays out of the way",
          body:
            "Clients regularly want to order or request new types of design from the business. The request form is deliberately elaborate — it has to capture enough for the factory to act on — but it lives inside the hamburger rather than the main flow, because it would otherwise clutter the path that every buyer takes for the business to keep making new designs every time.",
          textSide: "left",
          media: [
            {
              id: "feature-design-request",
              src: `${A}/design-request.webp`,
              label:
                "The new-design request form, step one — design type, product category and distributor, before any of the detail the factory needs.",
            },
            {
              id: "feature-design-request-2",
              src: `${A}/design-request-2.webp`,
              label:
                "Step two — the specification the factory acts on, gathered once rather than negotiated over email.",
            },
            {
              id: "feature-design-request-3",
              src: `${A}/design-request-3.webp`,
              label:
                "Step three — review before submission, so a request that will become a manufacturing job is confirmed deliberately.",
            },
          ],
        },
        {
          tagline: "The reorder path the traditional buyer forced.",
          title: "Orders that carry their own history",
          constraintLabel: "The constraint",
          constraint:
            "Mohan reorders known lines from memory or a spreadsheet, and fears overstock. Reordering could not begin with typing a design number.",
          body:
            "Past orders are a first-class surface rather than buried history. Current orders expose real state — ongoing, order placed, on hold — so a buyer waiting on gold knows where it is without a phone call. Completed orders put re-order on every row: the fastest path to a repeat purchase is the record of the last one.",
          textSide: "right",
          media: [
            {
              id: "feature-orders-ongoing",
              src: `${A}/orders-ongoing.webp`,
              label:
                "Current orders — each line carrying its OC number, reference number, net weight and an explicit status: ongoing, order placed, or on hold.",
            },
            {
              id: "feature-orders-completed",
              src: `${A}/orders-completed.webp`,
              label:
                "Completed orders — re-order on every row, so a repeat purchase never starts from a remembered design number.",
            },
          ],
        },
        {
          tagline: "The states nobody screenshots.",
          title: "Onboarding and failure, designed on purpose",
          body:
            "Sign-up captures GSTIN and company name because this is a B2B account, not a consumer one — the business relationship is established at the door rather than reconstructed later. The error and not-found states were designed rather than defaulted: on a platform where a buyer is committing to a bulk gold order, an unexplained failure is expensive to trust.",
          textSide: "left",
          media: [
            {
              id: "feature-sign-up",
              src: `${A}/sign-up.webp`,
              label:
                "Sign-up — GSTIN and company name alongside the usual fields, because every account here is a business account.",
            },
            {
              id: "feature-not-found",
              src: `${A}/not-found.webp`,
              label:
                "The not-found state — in the product's own voice, with a way back rather than a dead end.",
            },
            {
              id: "feature-error",
              src: `${A}/error-state.webp`,
              label:
                "The error state — plain language and an assurance that it is being handled, on a platform where trust is the product.",
            },
          ],
        },
      ],
    },

    /* ── 06 TRADE-OFFS ───────────────────────────────────────────────────── */
    {
      kind: "prose",
      id: "decisions",
      n: "06",
      heading: "Trade-offs",
      blocks: [
        {
          t: "lede",
          text:
            "Three decisions where the obvious option was cheaper to build and worse to use.",
        },
        {
          t: "decisionText",
          n: "01",
          heading:
            "Two ID systems that had to coexist without a human translating",
          cards: [
            {
              kind: "tempting",
              label: "The tempting option:",
              body:
                "Standardise on ORO's internal design numbers. One source of truth, no mapping layer, least to build.",
            },
            {
              kind: "problem",
              label: "The problem:",
              body:
                "It moves the entire cost onto the client. Buyers already track their orders by their own custom IDs inside their own systems — telling them to adopt ORO's vocabulary means they either maintain a translation sheet forever or keep calling ORO to translate for them. That is the exact dependency this project existed to remove.",
            },
            {
              kind: "chose",
              label: "What I chose instead:",
              body:
                "A two-level reference system on the client side, reconciled against the factory's own encoding. A Global Reference No names one instance of a bulk order. A Product Reference No names one customised product inside it — so two products sharing a design but differing in detail may or may not share a reference, which is why it is a checkbox state that lets a buyer change one type of product order or several at once. Underneath, the Design No and Job Work No stay unique and factory-generated.",
            },
            {
              kind: "why",
              label: "Why?:",
              body: [
                {
                  lead: "The system should absorb the complexity, not the customer.",
                  text:
                    "Both parties already had working vocabularies. The failure was never that one of them was wrong — it was that the software refused to speak either one fluently.",
                },
                {
                  lead: "It only works as a pair.",
                  text:
                    "Client-side references alone would drift from what the factory builds; factory numbers alone are what forced the phone calls. Holding both, and agreeing them on the same order, is what lets client and business navigate to a specific order need without a human translating.",
                },
              ],
            },
          ],
          img: `${A}/cart.webp`,
          imgAlt:
            "The reference-number system in the cart — a Global Reference No for the whole order, a Product Reference No per line, each reconciled against the factory's own Design No.",
        },
        {
          t: "decisionText",
          n: "02",
          heading: "Search that could not return text across the full catalogue",
          cards: [
            {
              kind: "tempting",
              label: "The tempting option:",
              body:
                "A conventional free-text search bar over everything, and accept that it is slow or incomplete at 70,000 entries.",
            },
            {
              kind: "problem",
              label: "The problem:",
              body:
                "A search that returns slowly, or returns nothing useful, teaches buyers not to use search. They fall back to asking someone at ORO — which is the behaviour the whole project was trying to end.",
            },
            {
              kind: "chose",
              label: "What I chose instead:",
              body:
                "An intent filter in the search bar that scopes the query before it is sent, so the backend answers a narrow question quickly instead of a broad one slowly.",
            },
            {
              kind: "why",
              label: "Why?:",
              body: [
                {
                  lead: "The constraint and the user need pointed the same way.",
                  text:
                    "A backend limit forced the scoping, but a bulk buyer browsing an assortment usually has a category and a price band rather than an exact string. The technical ceiling produced a better interaction than an unconstrained search would have.",
                },
              ],
            },
          ],
        },
        {
          t: "decisionText",
          n: "03",
          heading: "A cart carrying more information than any one screen should",
          cards: [
            {
              kind: "tempting",
              label: "The tempting option:",
              body:
                "Simplify the cart. Show line items and totals, push specifications and customisation into a separate step.",
            },
            {
              kind: "problem",
              label: "The problem:",
              body:
                "Hiding specifications is fine for a consumer buying one item and dangerous for a distributor approving a large order. If verifying the order means opening every line separately, buyers stop verifying — and an error found after production is enormously more expensive than one found in the cart.",
            },
            {
              kind: "chose",
              label: "What I chose instead:",
              body:
                "Keep everything on one surface and spend the design effort on structure — hierarchy, grouping and editable-in-place customisation, so density stays scannable rather than becoming noise.",
            },
            {
              kind: "why",
              label: "Why?:",
              body: [
                {
                  lead: "Low cognitive load is not the same as little information.",
                  text:
                    "The buyer needs all of it. What they do not need is to hunt for it. The work was in making a dense screen legible, not in making it smaller.",
                },
              ],
            },
          ],
        },
      ],
    },

    /* ── 07 IMPACT ───────────────────────────────────────────────────────── */
    {
      kind: "prose",
      id: "impact",
      n: "07",
      heading: "Impact",
      blocks: [
        {
          t: "heading",
          text: "A second product, not a squeezed one",
        },
        {
          t: "p",
          text:
            "I designed a separate mobile version whose entire purpose was making bulk ordering easy on a phone. Buyers on the road — walking a shop floor, standing in a supplier's showroom — were never going to complete a multi-line gold order on a shrunk-down desktop grid, and treating mobile as a responsive afterthought would have quietly excluded the traditional buyers who are least likely to be at a desk.",
        },
        { t: "sceneBreak" },
        {
          t: "heading",
          text: "What the redesign actually changed",
        },
        {
          t: "leadP",
          lead: "Ordering stopped depending on memory.",
          text:
            "The old flow required buyers to produce internal design numbers before they could transact. The new one lets them recognise products visually, search by intent, and reorder from history — removing the single most common cause of both mistyped orders and support calls.",
        },
        {
          t: "leadP",
          lead: "The backend dependency became a design problem, and got solved as one.",
          text:
            "Every workaround the old system relied on — phone calls to confirm design numbers, humans translating between two ID schemes, spreadsheets kept on the client side — was an interface gap being patched by labour. Carrying both identifiers natively removed the translation work rather than automating it.",
        },
        {
          t: "leadP",
          lead: "It was built to scale with the inventory, not just to fit it.",
          text:
            "70,000+ SKUs was the starting condition, not the ceiling. Intent-scoped search and a discovery-led landing page both hold up as the catalogue grows, where a text-match search over a flat list degrades with every product added.",
        },
        {
          t: "leadP",
          lead: "It shipped as a handoff, and was specified to survive one.",
          text:
            "Using an established design system and documenting the flows meant the engineering team inherited something buildable rather than a set of screenshots — the difference between a design that ships and a design that gets reinterpreted.",
        },
        { t: "sceneBreak" },
        {
          t: "subhead",
          text: "What I would do differently",
        },
        {
          t: "p",
          text:
            "I did not instrument anything. There were no analytics on the old flow and none specified for the new one, which means the improvement above is reasoned from the interaction design rather than measured — and the honest version of this case study has to say so. On any comparable project now, the first thing I would agree with stakeholders is what we are going to measure and how we will know it worked.",
        },
        {
          t: "p",
          text:
            "The second is that I designed for four personas without ever putting the prototype in front of one. The profiles came from stakeholder knowledge, which is real but secondhand. A single session with an actual bulk buyer would have tested the reorder path and the cart far more sharply than any amount of internal review did.",
        },
      ],
    },
  ],
};
