/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
  | ({
      _key: string;
    } & ImageGallery)
  | ({
      _key: string;
    } & VideoEmbed)
  | ({
      _key: string;
    } & MetricCallout)
  | ({
      _key: string;
    } & Quote)
  | ({
      _key: string;
    } & TwoColumn)
  | ({
      _key: string;
    } & FullBleedMedia)
  | ({
      _key: string;
    } & CaptionedFigure)
  | ({
      _key: string;
    } & ProcessStep)
>;

export type ProcessStep = {
  _type: "processStep";
  stepNumber?: number;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  media?: ImageWithAlt;
};

export type CaptionedFigure = {
  _type: "captionedFigure";
  image?: ImageWithAlt;
  caption?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<
      {
        _key: string;
      } & Link
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  width?: "inset" | "full";
};

export type FullBleedMedia = {
  _type: "fullBleedMedia";
  mediaType?: "image" | "video";
  image?: ImageWithAlt;
  video?: VideoEmbed;
  caption?: string;
  parallax?: boolean;
};

export type TwoColumn = {
  _type: "twoColumn";
  left?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
    | ({
        _key: string;
      } & MetricCallout)
  >;
  right?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
    | ({
        _key: string;
      } & MetricCallout)
  >;
  ratio?: "1-1" | "3-2" | "2-3";
};

export type Quote = {
  _type: "quote";
  text?: string;
  attribution?: string;
  role?: string;
};

export type MetricCallout = {
  _type: "metricCallout";
  value?: string;
  label?: string;
  description?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type VideoEmbed = {
  _type: "videoEmbed";
  url?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: ImageWithAlt;
  caption?: string;
  autoplay?: boolean;
};

export type ImageGallery = {
  _type: "imageGallery";
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  layout?: "grid" | "carousel" | "masonry";
  columns?: 2 | 3 | 4;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
  isExternal?: boolean;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: ImageWithAlt;
  thumbnail?: ImageWithAlt;
  featured?: boolean;
  context?: string;
  year?: string;
  role?: Array<string>;
  team?: string;
  timeline?: string;
  tags?: Array<string>;
  accentColor?: string;
  metrics?: Array<
    {
      _key: string;
    } & MetricCallout
  >;
  body?: RichContent;
  nextProject?: ProjectReference;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  headline?: string;
  portrait?: ImageWithAlt;
  bio?: RichContent;
  skills?: Array<{
    category?: string;
    items?: Array<string>;
    _type: "skillGroup";
    _key: string;
  }>;
  tools?: Array<string>;
  experience?: Array<{
    role?: string;
    company?: string;
    period?: string;
    summary?: string;
    _type: "role";
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  email?: string;
  resumeUrl?: string;
  nav?: Array<
    {
      _key: string;
    } & Link
  >;
  socials?: Array<
    {
      _key: string;
    } & Link
  >;
  footerText?: string;
  defaultSeo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichContent
  | ProcessStep
  | CaptionedFigure
  | FullBleedMedia
  | TwoColumn
  | Quote
  | MetricCallout
  | SanityFileAssetReference
  | VideoEmbed
  | ImageGallery
  | SanityImageAssetReference
  | ImageWithAlt
  | Seo
  | Link
  | ProjectReference
  | Project
  | Slug
  | Profile
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    title,    tagline,    email,    resumeUrl,    footerText,    nav[]{ label, "href": href, isExternal },    socials[]{ label, "href": href, isExternal },    defaultSeo  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  tagline: string | null;
  email: string | null;
  resumeUrl: string | null;
  footerText: string | null;
  nav: Array<{
    label: string | null;
    href: string | null;
    isExternal: boolean | null;
  }> | null;
  socials: Array<{
    label: string | null;
    href: string | null;
    isExternal: boolean | null;
  }> | null;
  defaultSeo: Seo | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile"][0]{    name,    headline,    portrait{   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    bio,    skills[]{ category, items },    tools,    experience[]{ role, company, period, summary },    seo  }
export type PROFILE_QUERY_RESULT = {
  name: string | null;
  headline: string | null;
  portrait: {
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  bio: RichContent | null;
  skills: Array<{
    category: string | null;
    items: Array<string> | null;
  }> | null;
  tools: Array<string> | null;
  experience: Array<{
    role: string | null;
    company: string | null;
    period: string | null;
    summary: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]    | order(orderRank){        _id,  title,  "slug": slug.current,  summary,  year,  context,  tags,  featured,  accentColor,  "cover": coalesce(thumbnail, coverImage){   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions }    }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  year: string | null;
  context: string | null;
  tags: Array<string> | null;
  featured: boolean | null;
  accentColor: string | null;
  cover: {
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true && defined(slug.current)]    | order(orderRank){        _id,  title,  "slug": slug.current,  summary,  year,  context,  tags,  featured,  accentColor,  "cover": coalesce(thumbnail, coverImage){   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions }    }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  year: string | null;
  context: string | null;
  tags: Array<string> | null;
  featured: boolean | null;
  accentColor: string | null;
  cover: {
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{ "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    context,    year,    role,    team,    timeline,    tags,    accentColor,    coverImage{   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    metrics[]{ value, label, description },    body[]{      ...,      _type == "imageWithAlt" => {   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },      _type == "captionedFigure" => { ..., image{   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions } },      _type == "fullBleedMedia" => { ..., image{   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions } },      _type == "imageGallery" => { ..., images[]{   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions } },      _type == "processStep" => { ..., media{   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions } }    },    seo,    "next": nextProject->{      title,      "slug": slug.current,      "cover": coalesce(thumbnail, coverImage){   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions }    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  context: string | null;
  year: string | null;
  role: Array<string> | null;
  team: string | null;
  timeline: string | null;
  tags: Array<string> | null;
  accentColor: string | null;
  coverImage: {
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  metrics: Array<{
    value: string | null;
    label: string | null;
    description: string | null;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          {
            _key: string;
          } & Link
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "captionedFigure";
        image: {
          _type: "imageWithAlt";
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<
            {
              _key: string;
            } & Link
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        width?: "full" | "inset";
      }
    | {
        _key: string;
        _type: "fullBleedMedia";
        mediaType?: "image" | "video";
        image: {
          _type: "imageWithAlt";
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
        video?: VideoEmbed;
        caption?: string;
        parallax?: boolean;
      }
    | {
        _key: string;
        _type: "imageGallery";
        images: Array<{
          _key: string;
          _type: "imageWithAlt";
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        }> | null;
        layout?: "carousel" | "grid" | "masonry";
        columns?: 2 | 3 | 4;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      }
    | {
        _key: string;
        _type: "metricCallout";
        value?: string;
        label?: string;
        description?: string;
      }
    | {
        _key: string;
        _type: "processStep";
        stepNumber?: number;
        title?: string;
        description?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        media: {
          _type: "imageWithAlt";
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      }
    | {
        _key: string;
        _type: "quote";
        text?: string;
        attribution?: string;
        role?: string;
      }
    | {
        _key: string;
        _type: "twoColumn";
        left?: Array<
          | ({
              _key: string;
            } & ImageWithAlt)
          | ({
              _key: string;
            } & MetricCallout)
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?:
                | "blockquote"
                | "h1"
                | "h2"
                | "h3"
                | "h4"
                | "h5"
                | "h6"
                | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
        >;
        right?: Array<
          | ({
              _key: string;
            } & ImageWithAlt)
          | ({
              _key: string;
            } & MetricCallout)
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?:
                | "blockquote"
                | "h1"
                | "h2"
                | "h3"
                | "h4"
                | "h5"
                | "h6"
                | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
        >;
        ratio?: "1-1" | "2-3" | "3-2";
      }
    | {
        _key: string;
        _type: "videoEmbed";
        url?: string;
        file?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        poster?: ImageWithAlt;
        caption?: string;
        autoplay?: boolean;
      }
  > | null;
  seo: Seo | null;
  next: {
    title: string | null;
    slug: string | null;
    cover: {
      _type: "imageWithAlt";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    title,\n    tagline,\n    email,\n    resumeUrl,\n    footerText,\n    nav[]{ label, "href": href, isExternal },\n    socials[]{ label, "href": href, isExternal },\n    defaultSeo\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "profile"][0]{\n    name,\n    headline,\n    portrait{ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    bio,\n    skills[]{ category, items },\n    tools,\n    experience[]{ role, company, period, summary },\n    seo\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]\n    | order(orderRank){\n      \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  year,\n  context,\n  tags,\n  featured,\n  accentColor,\n  "cover": coalesce(thumbnail, coverImage){ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n }\n\n    }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && featured == true && defined(slug.current)]\n    | order(orderRank){\n      \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  year,\n  context,\n  tags,\n  featured,\n  accentColor,\n  "cover": coalesce(thumbnail, coverImage){ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n }\n\n    }\n': FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{ "slug": slug.current }\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    context,\n    year,\n    role,\n    team,\n    timeline,\n    tags,\n    accentColor,\n    coverImage{ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    metrics[]{ value, label, description },\n    body[]{\n      ...,\n      _type == "imageWithAlt" => { \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n      _type == "captionedFigure" => { ..., image{ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n } },\n      _type == "fullBleedMedia" => { ..., image{ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n } },\n      _type == "imageGallery" => { ..., images[]{ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n } },\n      _type == "processStep" => { ..., media{ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n } }\n    },\n    seo,\n    "next": nextProject->{\n      title,\n      "slug": slug.current,\n      "cover": coalesce(thumbnail, coverImage){ \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n }\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
  }
}
