import { DEMO_POLISHED_RESPONSES } from '../data/demo-scenario';
import type { SectionAssistArgs } from './ai-report-service';

function simulateLatency(minMs = 1200, maxMs = 2800): Promise<void> {
  const delay = minMs + Math.random() * (maxMs - minMs);
  return new Promise((resolve) => setTimeout(resolve, delay));
}

export async function demoAssistSection(
  args: SectionAssistArgs
): Promise<{ content?: string; immediate?: string[]; shortTerm?: string[]; longTerm?: string[] }> {
  await simulateLatency();

  switch (args.target) {
    case 'executive_summary':
      return { content: DEMO_POLISHED_RESPONSES.executive_summary };

    case 'perimeter_status':
      return { content: DEMO_POLISHED_RESPONSES.perimeter_status };

    case 'compliance':
      return { content: DEMO_POLISHED_RESPONSES.compliance };

    case 'custom':
      return {
        content: `This is a demo-generated custom section titled "${args.sectionName || 'Custom section'}". In production, this section would be generated by the AI based on the agent's configuration, the template's prompt instruction, and any pilot draft content you provide.`,
      };

    case 'observation_description': {
      const number = args.observation?.number ?? 0;
      const polished = DEMO_POLISHED_RESPONSES.observations[number];
      if (polished) {
        return { content: polished };
      }
      const pilotContext = args.observation?.pilotContext || 'no context provided';
      const imageCount = args.observation?.imageLabels?.length || 0;
      return {
        content: `Based on the pilot observation "${pilotContext}", this finding has been documented with ${imageCount} supporting image${imageCount !== 1 ? 's' : ''}. In production, this description would be expanded by the vision-capable AI using both the pilot's first-hand context and visual analysis of the attached imagery.`,
      };
    }

    case 'recommendations':
      return {
        immediate: DEMO_POLISHED_RESPONSES.recommendations_immediate,
        shortTerm: [],
        longTerm: DEMO_POLISHED_RESPONSES.recommendations_long,
      };
  }

  return { content: '' };
}

export async function demoGenerateFullReport(): Promise<any> {
  await simulateLatency(3000, 5000);
  return {
    title: 'Night Shift Summary — Skybase Alpha — Apr 14',
    executiveSummary: DEMO_POLISHED_RESPONSES.executive_summary,
    observations: [],
    sectionContents: {},
    recommendations: {
      immediate: DEMO_POLISHED_RESPONSES.recommendations_immediate,
      shortTerm: [],
      longTerm: DEMO_POLISHED_RESPONSES.recommendations_long,
    },
  };
}

export async function demoFillSiteContext(): Promise<any> {
  await simulateLatency(1000, 2000);
  return {
    description: 'High-security industrial facility with drone patrol coverage across multiple perimeter sectors.',
    siteType: 'Industrial facility',
    timezone: 'Asia/Kolkata (IST)',
    operatingHours: '24/7',
    location: 'Demo location',
    context: 'Demo site context — in production the AI would infer rich context from your FlytBase site data.',
  };
}
