/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SendVerificationEmailRouteImport } from './routes/send-verification-email'
import { Route as RestrictedRouteImport } from './routes/restricted'
import { Route as OrgNotAccessibleRouteImport } from './routes/org-not-accessible'
import { Route as NoSitesRouteImport } from './routes/no-sites'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginErrorRouteImport } from './routes/login-error'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkSentRouteImport } from './routes/link-sent'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout/templates'
import { Route as LayoutSitesRouteImport } from './routes/_layout/sites'
import { Route as LayoutGuidesRouteImport } from './routes/_layout/guides'
import { Route as LayoutFlightsRouteImport } from './routes/_layout/flights'
import { Route as LayoutDraftsRouteImport } from './routes/_layout/drafts'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth/callback/google'
import { Route as LayoutTemplateTemplateIdRouteImport } from './routes/_layout/template.$templateId'
import { Route as LayoutSiteSiteIdRouteImport } from './routes/_layout/site.$siteId'
import { Route as LayoutReportReportIdRouteImport } from './routes/_layout/report.$reportId'
import { Route as LayoutReportPreviewReportIdRouteImport } from './routes/_layout/report-preview.$reportId'
import { Route as LayoutFlightFlightIdRouteImport } from './routes/_layout/flight.$flightId'
import { Route as LayoutAgentAgentIdRouteImport } from './routes/_layout/agent.$agentId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SendVerificationEmailRoute = SendVerificationEmailRouteImport.update({
  id: '/send-verification-email',
  path: '/send-verification-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedRoute = RestrictedRouteImport.update({
  id: '/restricted',
  path: '/restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgNotAccessibleRoute = OrgNotAccessibleRouteImport.update({
  id: '/org-not-accessible',
  path: '/org-not-accessible',
  getParentRoute: () => rootRouteImport,
} as any)
const NoSitesRoute = NoSitesRouteImport.update({
  id: '/no-sites',
  path: '/no-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginErrorRoute = LoginErrorRouteImport.update({
  id: '/login-error',
  path: '/login-error',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkSentRoute = LinkSentRouteImport.update({
  id: '/link-sent',
  path: '/link-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSitesRoute = LayoutSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuidesRoute = LayoutGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFlightsRoute = LayoutFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDraftsRoute = LayoutDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTemplateTemplateIdRoute =
  LayoutTemplateTemplateIdRouteImport.update({
    id: '/template/$templateId',
    path: '/template/$templateId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSiteSiteIdRoute = LayoutSiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportReportIdRoute = LayoutReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportPreviewReportIdRoute =
  LayoutReportPreviewReportIdRouteImport.update({
    id: '/report-preview/$reportId',
    path: '/report-preview/$reportId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFlightFlightIdRoute = LayoutFlightFlightIdRouteImport.update({
  id: '/flight/$flightId',
  path: '/flight/$flightId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentAgentIdRoute = LayoutAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/link-sent': typeof LinkSentRoute
  '/login': typeof LoginRoute
  '/login-error': typeof LoginErrorRoute
  '/logout': typeof LogoutRoute
  '/no-sites': typeof NoSitesRoute
  '/org-not-accessible': typeof OrgNotAccessibleRoute
  '/restricted': typeof RestrictedRoute
  '/send-verification-email': typeof SendVerificationEmailRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agents': typeof LayoutAgentsRoute
  '/drafts': typeof LayoutDraftsRoute
  '/flights': typeof LayoutFlightsRoute
  '/guides': typeof LayoutGuidesRoute
  '/sites': typeof LayoutSitesRoute
  '/templates': typeof LayoutTemplatesRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRoute
  '/flight/$flightId': typeof LayoutFlightFlightIdRoute
  '/report-preview/$reportId': typeof LayoutReportPreviewReportIdRoute
  '/report/$reportId': typeof LayoutReportReportIdRoute
  '/site/$siteId': typeof LayoutSiteSiteIdRoute
  '/template/$templateId': typeof LayoutTemplateTemplateIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/link-sent': typeof LinkSentRoute
  '/login': typeof LoginRoute
  '/login-error': typeof LoginErrorRoute
  '/logout': typeof LogoutRoute
  '/no-sites': typeof NoSitesRoute
  '/org-not-accessible': typeof OrgNotAccessibleRoute
  '/restricted': typeof RestrictedRoute
  '/send-verification-email': typeof SendVerificationEmailRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agents': typeof LayoutAgentsRoute
  '/drafts': typeof LayoutDraftsRoute
  '/flights': typeof LayoutFlightsRoute
  '/guides': typeof LayoutGuidesRoute
  '/sites': typeof LayoutSitesRoute
  '/templates': typeof LayoutTemplatesRoute
  '/': typeof LayoutIndexRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRoute
  '/flight/$flightId': typeof LayoutFlightFlightIdRoute
  '/report-preview/$reportId': typeof LayoutReportPreviewReportIdRoute
  '/report/$reportId': typeof LayoutReportReportIdRoute
  '/site/$siteId': typeof LayoutSiteSiteIdRoute
  '/template/$templateId': typeof LayoutTemplateTemplateIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/link-sent': typeof LinkSentRoute
  '/login': typeof LoginRoute
  '/login-error': typeof LoginErrorRoute
  '/logout': typeof LogoutRoute
  '/no-sites': typeof NoSitesRoute
  '/org-not-accessible': typeof OrgNotAccessibleRoute
  '/restricted': typeof RestrictedRoute
  '/send-verification-email': typeof SendVerificationEmailRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/drafts': typeof LayoutDraftsRoute
  '/_layout/flights': typeof LayoutFlightsRoute
  '/_layout/guides': typeof LayoutGuidesRoute
  '/_layout/sites': typeof LayoutSitesRoute
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/agent/$agentId': typeof LayoutAgentAgentIdRoute
  '/_layout/flight/$flightId': typeof LayoutFlightFlightIdRoute
  '/_layout/report-preview/$reportId': typeof LayoutReportPreviewReportIdRoute
  '/_layout/report/$reportId': typeof LayoutReportReportIdRoute
  '/_layout/site/$siteId': typeof LayoutSiteSiteIdRoute
  '/_layout/template/$templateId': typeof LayoutTemplateTemplateIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/link-sent'
    | '/login'
    | '/login-error'
    | '/logout'
    | '/no-sites'
    | '/org-not-accessible'
    | '/restricted'
    | '/send-verification-email'
    | '/signup'
    | '/verify'
    | '/verify-email'
    | '/agents'
    | '/drafts'
    | '/flights'
    | '/guides'
    | '/sites'
    | '/templates'
    | '/agent/$agentId'
    | '/flight/$flightId'
    | '/report-preview/$reportId'
    | '/report/$reportId'
    | '/site/$siteId'
    | '/template/$templateId'
    | '/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/link-sent'
    | '/login'
    | '/login-error'
    | '/logout'
    | '/no-sites'
    | '/org-not-accessible'
    | '/restricted'
    | '/send-verification-email'
    | '/signup'
    | '/verify'
    | '/verify-email'
    | '/agents'
    | '/drafts'
    | '/flights'
    | '/guides'
    | '/sites'
    | '/templates'
    | '/'
    | '/agent/$agentId'
    | '/flight/$flightId'
    | '/report-preview/$reportId'
    | '/report/$reportId'
    | '/site/$siteId'
    | '/template/$templateId'
    | '/auth/callback/google'
  id:
    | '__root__'
    | '/_layout'
    | '/link-sent'
    | '/login'
    | '/login-error'
    | '/logout'
    | '/no-sites'
    | '/org-not-accessible'
    | '/restricted'
    | '/send-verification-email'
    | '/signup'
    | '/verify'
    | '/verify-email'
    | '/_layout/agents'
    | '/_layout/drafts'
    | '/_layout/flights'
    | '/_layout/guides'
    | '/_layout/sites'
    | '/_layout/templates'
    | '/_layout/'
    | '/_layout/agent/$agentId'
    | '/_layout/flight/$flightId'
    | '/_layout/report-preview/$reportId'
    | '/_layout/report/$reportId'
    | '/_layout/site/$siteId'
    | '/_layout/template/$templateId'
    | '/auth/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LinkSentRoute: typeof LinkSentRoute
  LoginRoute: typeof LoginRoute
  LoginErrorRoute: typeof LoginErrorRoute
  LogoutRoute: typeof LogoutRoute
  NoSitesRoute: typeof NoSitesRoute
  OrgNotAccessibleRoute: typeof OrgNotAccessibleRoute
  RestrictedRoute: typeof RestrictedRoute
  SendVerificationEmailRoute: typeof SendVerificationEmailRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-verification-email': {
      id: '/send-verification-email'
      path: '/send-verification-email'
      fullPath: '/send-verification-email'
      preLoaderRoute: typeof SendVerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restricted': {
      id: '/restricted'
      path: '/restricted'
      fullPath: '/restricted'
      preLoaderRoute: typeof RestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-not-accessible': {
      id: '/org-not-accessible'
      path: '/org-not-accessible'
      fullPath: '/org-not-accessible'
      preLoaderRoute: typeof OrgNotAccessibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-sites': {
      id: '/no-sites'
      path: '/no-sites'
      fullPath: '/no-sites'
      preLoaderRoute: typeof NoSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-error': {
      id: '/login-error'
      path: '/login-error'
      fullPath: '/login-error'
      preLoaderRoute: typeof LoginErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-sent': {
      id: '/link-sent'
      path: '/link-sent'
      fullPath: '/link-sent'
      preLoaderRoute: typeof LinkSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sites': {
      id: '/_layout/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof LayoutSitesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guides': {
      id: '/_layout/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof LayoutGuidesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/flights': {
      id: '/_layout/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof LayoutFlightsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/drafts': {
      id: '/_layout/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof LayoutDraftsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/template/$templateId': {
      id: '/_layout/template/$templateId'
      path: '/template/$templateId'
      fullPath: '/template/$templateId'
      preLoaderRoute: typeof LayoutTemplateTemplateIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/site/$siteId': {
      id: '/_layout/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof LayoutSiteSiteIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/report/$reportId': {
      id: '/_layout/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof LayoutReportReportIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/report-preview/$reportId': {
      id: '/_layout/report-preview/$reportId'
      path: '/report-preview/$reportId'
      fullPath: '/report-preview/$reportId'
      preLoaderRoute: typeof LayoutReportPreviewReportIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/flight/$flightId': {
      id: '/_layout/flight/$flightId'
      path: '/flight/$flightId'
      fullPath: '/flight/$flightId'
      preLoaderRoute: typeof LayoutFlightFlightIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent/$agentId': {
      id: '/_layout/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof LayoutAgentAgentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutDraftsRoute: typeof LayoutDraftsRoute
  LayoutFlightsRoute: typeof LayoutFlightsRoute
  LayoutGuidesRoute: typeof LayoutGuidesRoute
  LayoutSitesRoute: typeof LayoutSitesRoute
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAgentAgentIdRoute: typeof LayoutAgentAgentIdRoute
  LayoutFlightFlightIdRoute: typeof LayoutFlightFlightIdRoute
  LayoutReportPreviewReportIdRoute: typeof LayoutReportPreviewReportIdRoute
  LayoutReportReportIdRoute: typeof LayoutReportReportIdRoute
  LayoutSiteSiteIdRoute: typeof LayoutSiteSiteIdRoute
  LayoutTemplateTemplateIdRoute: typeof LayoutTemplateTemplateIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutDraftsRoute: LayoutDraftsRoute,
  LayoutFlightsRoute: LayoutFlightsRoute,
  LayoutGuidesRoute: LayoutGuidesRoute,
  LayoutSitesRoute: LayoutSitesRoute,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAgentAgentIdRoute: LayoutAgentAgentIdRoute,
  LayoutFlightFlightIdRoute: LayoutFlightFlightIdRoute,
  LayoutReportPreviewReportIdRoute: LayoutReportPreviewReportIdRoute,
  LayoutReportReportIdRoute: LayoutReportReportIdRoute,
  LayoutSiteSiteIdRoute: LayoutSiteSiteIdRoute,
  LayoutTemplateTemplateIdRoute: LayoutTemplateTemplateIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LinkSentRoute: LinkSentRoute,
  LoginRoute: LoginRoute,
  LoginErrorRoute: LoginErrorRoute,
  LogoutRoute: LogoutRoute,
  NoSitesRoute: NoSitesRoute,
  OrgNotAccessibleRoute: OrgNotAccessibleRoute,
  RestrictedRoute: RestrictedRoute,
  SendVerificationEmailRoute: SendVerificationEmailRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
