import { defineField, defineType, defineArrayMember } from "sanity";
import { CaseIcon } from "@sanity/icons";
import { orderRankField, orderRankOrdering } from "@sanity/orderable-document-list";

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  icon: CaseIcon,
  orderings: [orderRankOrdering],
  groups: [
    { name: "overview", title: "Overview", default: true },
    { name: "meta", title: "Meta" },
    { name: "content", title: "Case study" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    orderRankField({ type: "project" }),
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "overview",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "summary",
      title: "Summary",
      type: "text",
      rows: 3,
      group: "overview",
      description: "Short description for cards and meta description.",
    }),
    defineField({
      name: "coverImage",
      title: "Cover image",
      type: "imageWithAlt",
      group: "overview",
    }),
    defineField({
      name: "thumbnail",
      title: "Thumbnail (optional)",
      type: "imageWithAlt",
      group: "overview",
      description: "Used in the work grid; falls back to cover image.",
    }),
    defineField({
      name: "featured",
      title: "Featured on home",
      type: "boolean",
      group: "overview",
      initialValue: false,
    }),
    defineField({
      name: "context",
      title: "Client / Context",
      type: "string",
      group: "meta",
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      group: "meta",
    }),
    defineField({
      name: "role",
      title: "Role",
      type: "array",
      group: "meta",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
    }),
    defineField({
      name: "team",
      title: "Team",
      type: "string",
      group: "meta",
    }),
    defineField({
      name: "timeline",
      title: "Timeline",
      type: "string",
      group: "meta",
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "meta",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
    }),
    defineField({
      name: "accentColor",
      title: "Accent color override",
      type: "string",
      group: "meta",
      description: "Optional hex for per-project theming. e.g. #4F46E5",
    }),
    defineField({
      name: "metrics",
      title: "Headline metrics",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "metricCallout" })],
    }),
    defineField({
      name: "body",
      title: "Case study content",
      type: "richContent",
      group: "content",
    }),
    defineField({
      name: "nextProject",
      title: "Next project",
      type: "reference",
      group: "content",
      to: [{ type: "project" }],
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "context", media: "coverImage" },
  },
});
