export default {
  displayName: 'shared-map',
  preset: '../../../jest.preset.js',
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nx/react/babel'] }],
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: './coverage',
  coverageReporters: ['html', 'text', 'json-summary', 'lcov'],
  collectCoverageFrom: [
    'src/private/map-providers/cesium/entities/**/*.ts',
    '!src/private/map-providers/cesium/entities/**/*.test.ts',
    '!src/private/map-providers/cesium/entities/**/*.spec.ts',
    '!src/private/map-providers/cesium/entities/**/*.mock.ts',
    '!**/*.d.ts',
    '!**/index.ts',
    '!**/node_modules/**',
    '!**/tests/**',
    '!**/coverage/**',
    '!**/dist/**',
  ],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  moduleNameMapper: {
    // Keep Jest path resolution aligned with the current library structure in `src/`
    '@map/public/(.*)$': '<rootDir>/src/public/$1',
    '@map/public$': '<rootDir>/src/public',
    '@map/private/(.*)$': '<rootDir>/src/private/$1',
    '@map/private$': '<rootDir>/src/private',
    '@map/(.*)$': '<rootDir>/$1',
    '@map$': '<rootDir>/index.ts',
    '@tests/(.*)$': '<rootDir>/tests/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup/jest.setup.ts'],
  clearMocks: true,
  restoreMocks: true,
  transformIgnorePatterns: ['node_modules/(?!(@cesium))'],
};
